(package
  (name pathname)
  (version "0.1.0")
  (license "BSD")
  (authors "Alex Shinn")
  (maintainers "Arthur Maciel <arthurmaciel at gmail dot com>")
  (description "A general, non-filesystem-specific pathname library")
  (tags "utils")
  (docs "https://github.com/cyclone-scheme/cyclone-winds/wiki/pathname")
  (test "test.scm")
  (dependencies (string))
  (test-dependencies ())
  (foreign-dependencies ())
  (library
    (name (cyclone pathname))
    (description "A general, non-filesystem-specific pathname library")))
